FROM node:22-alpine AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS dependencies
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_APP_CHECK_SITE_KEY
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_MEASURING_ID
ARG NEXT_PUBLIC_GITHUB_SPONSOR_URL
ARG NEXT_PUBLIC_LEGAL_OPERATOR_NAME
ARG NEXT_PUBLIC_LEGAL_OPERATOR_ADDRESS
ARG NEXT_PUBLIC_LEGAL_GOVERNING_LAW
ARG NEXT_PUBLIC_LEGAL_VENUE
ARG NEXT_PUBLIC_LEGAL_LIABILITY_CAP
ARG NEXT_PUBLIC_LEGAL_EFFECTIVE_DATE
ARG NEXT_PUBLIC_SUPPORT_EMAIL
ARG NEXT_PUBLIC_SECURITY_EMAIL
ARG NEXT_PUBLIC_PRIVACY_EMAIL
ARG NEXT_PUBLIC_SAFETY_EMAIL
ARG NEXT_PUBLIC_LEGAL_EMAIL
ARG NEXT_PUBLIC_SPONSORS_EMAIL

ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_APP_CHECK_SITE_KEY=$NEXT_PUBLIC_FIREBASE_APP_CHECK_SITE_KEY
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
ENV NEXT_PUBLIC_MEASURING_ID=$NEXT_PUBLIC_MEASURING_ID
ENV NEXT_PUBLIC_GITHUB_SPONSOR_URL=$NEXT_PUBLIC_GITHUB_SPONSOR_URL
ENV NEXT_PUBLIC_LEGAL_OPERATOR_NAME=$NEXT_PUBLIC_LEGAL_OPERATOR_NAME
ENV NEXT_PUBLIC_LEGAL_OPERATOR_ADDRESS=$NEXT_PUBLIC_LEGAL_OPERATOR_ADDRESS
ENV NEXT_PUBLIC_LEGAL_GOVERNING_LAW=$NEXT_PUBLIC_LEGAL_GOVERNING_LAW
ENV NEXT_PUBLIC_LEGAL_VENUE=$NEXT_PUBLIC_LEGAL_VENUE
ENV NEXT_PUBLIC_LEGAL_LIABILITY_CAP=$NEXT_PUBLIC_LEGAL_LIABILITY_CAP
ENV NEXT_PUBLIC_LEGAL_EFFECTIVE_DATE=$NEXT_PUBLIC_LEGAL_EFFECTIVE_DATE
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_SECURITY_EMAIL=$NEXT_PUBLIC_SECURITY_EMAIL
ENV NEXT_PUBLIC_PRIVACY_EMAIL=$NEXT_PUBLIC_PRIVACY_EMAIL
ENV NEXT_PUBLIC_SAFETY_EMAIL=$NEXT_PUBLIC_SAFETY_EMAIL
ENV NEXT_PUBLIC_LEGAL_EMAIL=$NEXT_PUBLIC_LEGAL_EMAIL
ENV NEXT_PUBLIC_SPONSORS_EMAIL=$NEXT_PUBLIC_SPONSORS_EMAIL

RUN npm run build:production

FROM base AS runner
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/scripts/validate-production-env.mjs ./scripts/validate-production-env.mjs

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["sh", "-c", "node ./scripts/validate-production-env.mjs hosted --production --runtime && exec node server.js"]
