import {
  FaApple,
  FaBehance,
  FaCodepen,
  FaDiscord,
  FaDribbble,
  FaEnvelope,
  FaFacebook,
  FaFigma,
  FaGithub,
  FaGitlab,
  FaInstagram,
  FaLinkedinIn,
  FaMedium,
  FaPatreon,
  FaProductHunt,
  FaRedditAlien,
  FaSoundcloud,
  FaSpotify,
  FaStackOverflow,
  FaTelegramPlane,
  FaTiktok,
  FaTwitch,
  FaWhatsapp,
  FaYoutube,
} from "react-icons/fa";
import {
  FaBluesky,
  FaHashnode,
  FaSquareThreads,
  FaXTwitter,
} from "react-icons/fa6";
import {
  SiBuymeacoffee,
  SiCalendly,
  SiCodesandbox,
  SiDevdotto,
  SiKofi,
  SiMastodon,
  SiNpm,
} from "react-icons/si";
import type { ReactNode } from "react";
import { FiCalendar, FiGlobe } from "react-icons/fi";
import type { SocialKey } from "@/lib/socials";

export const socialIcons: Record<SocialKey, ReactNode> = {
  github: <FaGithub aria-hidden="true" />,
  gitlab: <FaGitlab aria-hidden="true" />,
  linkedin: <FaLinkedinIn aria-hidden="true" />,
  x: <FaXTwitter aria-hidden="true" />,
  youtube: <FaYoutube aria-hidden="true" />,
  instagram: <FaInstagram aria-hidden="true" />,
  tiktok: <FaTiktok aria-hidden="true" />,
  facebook: <FaFacebook aria-hidden="true" />,
  threads: <FaSquareThreads aria-hidden="true" />,
  bluesky: <FaBluesky aria-hidden="true" />,
  mastodon: <SiMastodon aria-hidden="true" />,
  discord: <FaDiscord aria-hidden="true" />,
  twitch: <FaTwitch aria-hidden="true" />,
  reddit: <FaRedditAlien aria-hidden="true" />,
  medium: <FaMedium aria-hidden="true" />,
  hashnode: <FaHashnode aria-hidden="true" />,
  devto: <SiDevdotto aria-hidden="true" />,
  stackoverflow: <FaStackOverflow aria-hidden="true" />,
  codepen: <FaCodepen aria-hidden="true" />,
  codesandbox: <SiCodesandbox aria-hidden="true" />,
  dribbble: <FaDribbble aria-hidden="true" />,
  behance: <FaBehance aria-hidden="true" />,
  figma: <FaFigma aria-hidden="true" />,
  npm: <SiNpm aria-hidden="true" />,
  producthunt: <FaProductHunt aria-hidden="true" />,
  telegram: <FaTelegramPlane aria-hidden="true" />,
  whatsapp: <FaWhatsapp aria-hidden="true" />,
  spotify: <FaSpotify aria-hidden="true" />,
  soundcloud: <FaSoundcloud aria-hidden="true" />,
  apple_music: <FaApple aria-hidden="true" />,
  patreon: <FaPatreon aria-hidden="true" />,
  kofi: <SiKofi aria-hidden="true" />,
  buymeacoffee: <SiBuymeacoffee aria-hidden="true" />,
  calendly: <SiCalendly aria-hidden="true" />,
  calcom: <FiCalendar aria-hidden="true" />,
  email: <FaEnvelope aria-hidden="true" />,
  website: <FiGlobe aria-hidden="true" />,
};
