import type { IconType } from "react-icons";
import {
  FaAndroid,
  FaApple,
  FaBehance,
  FaCodepen,
  FaDiscord,
  FaDribbble,
  FaEnvelope,
  FaFacebook,
  FaFigma,
  FaGithub,
  FaGitlab,
  FaInstagram,
  FaLinkedinIn,
  FaMedium,
  FaPatreon,
  FaProductHunt,
  FaRedditAlien,
  FaSnapchat,
  FaSoundcloud,
  FaSpotify,
  FaStackOverflow,
  FaSteam,
  FaTelegramPlane,
  FaTiktok,
  FaTrello,
  FaTumblr,
  FaTwitch,
  FaVimeo,
  FaWhatsapp,
  FaYoutube,
} from "react-icons/fa";
import {
  FaAnchor,
  FaAward,
  FaBell,
  FaBicycle,
  FaBlog,
  FaBolt,
  FaBookOpen,
  FaBookmark,
  FaBox,
  FaBrain,
  FaBriefcase,
  FaBrush,
  FaBuilding,
  FaBullseye,
  FaBurger,
  FaCamera,
  FaCampground,
  FaCar,
  FaCartShopping,
  FaCat,
  FaCertificate,
  FaChalkboard,
  FaChartLine,
  FaChess,
  FaChild,
  FaClapperboard,
  FaClipboard,
  FaClock,
  FaCloud,
  FaComments,
  FaCompass,
  FaCopy,
  FaCrown,
  FaCube,
  FaDatabase,
  FaDice,
  FaDog,
  FaDragon,
  FaDrum,
  FaDumbbell,
  FaEarthAmericas,
  FaEthernet,
  FaEye,
  FaFeather,
  FaFilm,
  FaFingerprint,
  FaFire,
  FaFish,
  FaFlag,
  FaFlask,
  FaGamepad,
  FaGear,
  FaGem,
  FaGhost,
  FaGlasses,
  FaGraduationCap,
  FaGuitar,
  FaHammer,
  FaHandPeace,
  FaHandsClapping,
  FaHandshake,
  FaHardDrive,
  FaHashtag,
  FaHeadphones,
  FaHeartPulse,
  FaHelicopter,
  FaHorse,
  FaHouse,
  FaKeyboard,
  FaKey,
  FaLandmark,
  FaLaptop,
  FaLeaf,
  FaLightbulb,
  FaList,
  FaLocationDot,
  FaLock,
  FaMasksTheater,
  FaMagnifyingGlass,
  FaMedal,
  FaMessage,
  FaMicrochip,
  FaMicrophone,
  FaMicroscope,
  FaMoon,
  FaMountain,
  FaMugHot,
  FaNewspaper,
  FaPalette,
  FaPaintbrush,
  FaPaperclip,
  FaPaperPlane,
  FaPause,
  FaPaw,
  FaPen,
  FaPenNib,
  FaPeopleGroup,
  FaPercent,
  FaPersonHiking,
  FaPersonRunning,
  FaPhone,
  FaPizzaSlice,
  FaPlane,
  FaPlay,
  FaPlug,
  FaPodcast,
  FaPuzzlePiece,
  FaQrcode,
  FaRadio,
  FaRecycle,
  FaRibbon,
  FaRobot,
  FaRocket,
  FaRoute,
  FaRuler,
  FaSatellite,
  FaSchool,
  FaScissors,
  FaSeedling,
  FaServer,
  FaShareNodes,
  FaShieldHalved,
  FaShip,
  FaSignature,
  FaSkull,
  FaSliders,
  FaSpider,
  FaStamp,
  FaStore,
  FaStethoscope,
  FaSun,
  FaTablet,
  FaTag,
  FaTerminal,
  FaThumbsUp,
  FaTicket,
  FaToolbox,
  FaTrain,
  FaTree,
  FaTrophy,
  FaTruck,
  FaTv,
  FaUmbrella,
  FaUtensils,
  FaVolumeHigh,
  FaWalkieTalkie,
  FaWallet,
  FaWandMagicSparkles,
  FaWater,
  FaWheelchair,
  FaWifi,
  FaWineGlass,
  FaBluesky,
  FaHashnode,
  FaSquareThreads,
  FaXTwitter,
} from "react-icons/fa6";
import {
  FiBookmark,
  FiBook,
  FiCalendar,
  FiClock,
  FiCode,
  FiCoffee,
  FiCompass,
  FiCreditCard,
  FiDownload,
  FiExternalLink,
  FiFeather,
  FiFile,
  FiFilm,
  FiFlag,
  FiFolder,
  FiGift,
  FiGlobe,
  FiHeadphones,
  FiHeart,
  FiHome,
  FiImage,
  FiLayers,
  FiLink,
  FiMail,
  FiMapPin,
  FiMic,
  FiMonitor,
  FiMusic,
  FiPackage,
  FiPhone,
  FiPlay,
  FiSend,
  FiSettings,
  FiShare2,
  FiShield,
  FiShoppingBag,
  FiSmartphone,
  FiSpeaker,
  FiStar,
  FiSun,
  FiTarget,
  FiTerminal,
  FiTool,
  FiTrash2,
  FiTrendingUp,
  FiUser,
  FiUsers,
  FiVideo,
  FiWatch,
  FiZap,
} from "react-icons/fi";
import {
  SiAmazon,
  SiBandcamp,
  SiBuymeacoffee,
  SiCalendly,
  SiCloudflare,
  SiCodesandbox,
  SiConfluence,
  SiDevdotto,
  SiDocker,
  SiDropbox,
  SiFirebase,
  SiGhost,
  SiGoogle,
  SiGoogledrive,
  SiHeroku,
  SiItchdotio,
  SiJira,
  SiKofi,
  SiKubernetes,
  SiLinear,
  SiMastodon,
  SiMongodb,
  SiNetlify,
  SiNotion,
  SiNodedotjs,
  SiNpm,
  SiPaypal,
  SiPinterest,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRust,
  SiShopify,
  SiSlack,
  SiStripe,
  SiSubstack,
  SiSupabase,
  SiTypescript,
  SiVercel,
  SiWikipedia,
  SiWordpress,
} from "react-icons/si";

export type MediaIconEntry = {
  id: string;
  label: string;
  keywords: string[];
  Icon: IconType;
};

export const MEDIA_ICONS: MediaIconEntry[] = [
  { id: "github", label: "GitHub", keywords: ["git", "code", "repo"], Icon: FaGithub },
  { id: "gitlab", label: "GitLab", keywords: ["git", "code", "repo"], Icon: FaGitlab },
  { id: "linkedin", label: "LinkedIn", keywords: ["work", "professional"], Icon: FaLinkedinIn },
  { id: "x", label: "X", keywords: ["twitter", "social"], Icon: FaXTwitter },
  { id: "youtube", label: "YouTube", keywords: ["video", "watch"], Icon: FaYoutube },
  { id: "instagram", label: "Instagram", keywords: ["photo", "social"], Icon: FaInstagram },
  { id: "tiktok", label: "TikTok", keywords: ["video", "social"], Icon: FaTiktok },
  { id: "facebook", label: "Facebook", keywords: ["social", "meta"], Icon: FaFacebook },
  { id: "threads", label: "Threads", keywords: ["social", "meta"], Icon: FaSquareThreads },
  { id: "bluesky", label: "Bluesky", keywords: ["social"], Icon: FaBluesky },
  { id: "mastodon", label: "Mastodon", keywords: ["fediverse", "social"], Icon: SiMastodon },
  { id: "discord", label: "Discord", keywords: ["chat", "community"], Icon: FaDiscord },
  { id: "twitch", label: "Twitch", keywords: ["stream", "live"], Icon: FaTwitch },
  { id: "reddit", label: "Reddit", keywords: ["forum", "community"], Icon: FaRedditAlien },
  { id: "medium", label: "Medium", keywords: ["blog", "writing"], Icon: FaMedium },
  { id: "hashnode", label: "Hashnode", keywords: ["blog", "writing"], Icon: FaHashnode },
  { id: "devto", label: "Dev.to", keywords: ["blog", "developer"], Icon: SiDevdotto },
  { id: "substack", label: "Substack", keywords: ["newsletter", "writing"], Icon: SiSubstack },
  { id: "wordpress", label: "WordPress", keywords: ["blog", "cms"], Icon: SiWordpress },
  { id: "ghost", label: "Ghost", keywords: ["blog", "cms"], Icon: SiGhost },
  { id: "stackoverflow", label: "Stack Overflow", keywords: ["qa", "developer"], Icon: FaStackOverflow },
  { id: "codepen", label: "CodePen", keywords: ["demo", "frontend"], Icon: FaCodepen },
  { id: "codesandbox", label: "CodeSandbox", keywords: ["demo", "sandbox"], Icon: SiCodesandbox },
  { id: "npm", label: "npm", keywords: ["package", "javascript"], Icon: SiNpm },
  { id: "dribbble", label: "Dribbble", keywords: ["design", "portfolio"], Icon: FaDribbble },
  { id: "behance", label: "Behance", keywords: ["design", "portfolio"], Icon: FaBehance },
  { id: "figma", label: "Figma", keywords: ["design", "ui"], Icon: FaFigma },
  { id: "producthunt", label: "Product Hunt", keywords: ["launch", "startup"], Icon: FaProductHunt },
  { id: "telegram", label: "Telegram", keywords: ["chat", "message"], Icon: FaTelegramPlane },
  { id: "whatsapp", label: "WhatsApp", keywords: ["chat", "message"], Icon: FaWhatsapp },
  { id: "slack", label: "Slack", keywords: ["chat", "team"], Icon: SiSlack },
  { id: "notion", label: "Notion", keywords: ["notes", "docs"], Icon: SiNotion },
  { id: "confluence", label: "Confluence", keywords: ["docs", "wiki"], Icon: SiConfluence },
  { id: "jira", label: "Jira", keywords: ["project", "issues"], Icon: SiJira },
  { id: "linear", label: "Linear", keywords: ["project", "issues"], Icon: SiLinear },
  { id: "trello", label: "Trello", keywords: ["board", "tasks"], Icon: FaTrello },
  { id: "spotify", label: "Spotify", keywords: ["music", "audio"], Icon: FaSpotify },
  { id: "soundcloud", label: "SoundCloud", keywords: ["music", "audio"], Icon: FaSoundcloud },
  { id: "apple_music", label: "Apple Music", keywords: ["music", "audio"], Icon: FaApple },
  { id: "bandcamp", label: "Bandcamp", keywords: ["music", "album"], Icon: SiBandcamp },
  { id: "vimeo", label: "Vimeo", keywords: ["video"], Icon: FaVimeo },
  { id: "patreon", label: "Patreon", keywords: ["support", "creator"], Icon: FaPatreon },
  { id: "kofi", label: "Ko-fi", keywords: ["support", "tip"], Icon: SiKofi },
  { id: "buymeacoffee", label: "Buy Me a Coffee", keywords: ["support", "tip"], Icon: SiBuymeacoffee },
  { id: "paypal", label: "PayPal", keywords: ["payment", "money"], Icon: SiPaypal },
  { id: "stripe", label: "Stripe", keywords: ["payment", "billing"], Icon: SiStripe },
  { id: "shopify", label: "Shopify", keywords: ["store", "commerce"], Icon: SiShopify },
  { id: "amazon", label: "Amazon", keywords: ["store", "shop"], Icon: SiAmazon },
  { id: "calendly", label: "Calendly", keywords: ["calendar", "booking"], Icon: SiCalendly },
  { id: "google", label: "Google", keywords: ["search", "workspace"], Icon: SiGoogle },
  { id: "googledrive", label: "Google Drive", keywords: ["files", "cloud"], Icon: SiGoogledrive },
  { id: "dropbox", label: "Dropbox", keywords: ["files", "cloud"], Icon: SiDropbox },
  { id: "apple", label: "Apple", keywords: ["ios", "mac"], Icon: FaApple },
  { id: "android", label: "Android", keywords: ["mobile", "google"], Icon: FaAndroid },
  { id: "snapchat", label: "Snapchat", keywords: ["social", "photo"], Icon: FaSnapchat },
  { id: "pinterest", label: "Pinterest", keywords: ["social", "pins"], Icon: SiPinterest },
  { id: "tumblr", label: "Tumblr", keywords: ["blog", "social"], Icon: FaTumblr },
  { id: "steam", label: "Steam", keywords: ["game", "gaming"], Icon: FaSteam },
  { id: "itch", label: "itch.io", keywords: ["game", "indie"], Icon: SiItchdotio },
  { id: "wikipedia", label: "Wikipedia", keywords: ["wiki", "encyclopedia"], Icon: SiWikipedia },
  { id: "vercel", label: "Vercel", keywords: ["deploy", "hosting"], Icon: SiVercel },
  { id: "netlify", label: "Netlify", keywords: ["deploy", "hosting"], Icon: SiNetlify },
  { id: "heroku", label: "Heroku", keywords: ["deploy", "hosting"], Icon: SiHeroku },
  { id: "cloudflare", label: "Cloudflare", keywords: ["cdn", "dns"], Icon: SiCloudflare },
  { id: "docker", label: "Docker", keywords: ["container", "devops"], Icon: SiDocker },
  { id: "kubernetes", label: "Kubernetes", keywords: ["container", "devops"], Icon: SiKubernetes },
  { id: "firebase", label: "Firebase", keywords: ["google", "backend"], Icon: SiFirebase },
  { id: "supabase", label: "Supabase", keywords: ["database", "backend"], Icon: SiSupabase },
  { id: "mongodb", label: "MongoDB", keywords: ["database", "nosql"], Icon: SiMongodb },
  { id: "postgresql", label: "PostgreSQL", keywords: ["database", "sql"], Icon: SiPostgresql },
  { id: "react", label: "React", keywords: ["javascript", "frontend"], Icon: SiReact },
  { id: "typescript", label: "TypeScript", keywords: ["javascript", "types"], Icon: SiTypescript },
  { id: "nodejs", label: "Node.js", keywords: ["javascript", "backend"], Icon: SiNodedotjs },
  { id: "python", label: "Python", keywords: ["language", "script"], Icon: SiPython },
  { id: "rust", label: "Rust", keywords: ["language", "systems"], Icon: SiRust },
  { id: "link", label: "Link", keywords: ["url", "website"], Icon: FiLink },
  { id: "globe", label: "Website", keywords: ["web", "internet"], Icon: FiGlobe },
  { id: "mail", label: "Email", keywords: ["contact", "message"], Icon: FiMail },
  { id: "envelope", label: "Envelope", keywords: ["email", "letter"], Icon: FaEnvelope },
  { id: "book", label: "Book", keywords: ["read", "guide"], Icon: FiBook },
  { id: "code", label: "Code", keywords: ["developer", "programming"], Icon: FiCode },
  { id: "terminal", label: "Terminal", keywords: ["cli", "shell"], Icon: FiTerminal },
  { id: "file", label: "File", keywords: ["document", "download"], Icon: FiFile },
  { id: "folder", label: "Folder", keywords: ["directory", "collection"], Icon: FiFolder },
  { id: "image", label: "Image", keywords: ["photo", "picture"], Icon: FiImage },
  { id: "video", label: "Video", keywords: ["watch", "film"], Icon: FiVideo },
  { id: "music", label: "Music", keywords: ["audio", "song"], Icon: FiMusic },
  { id: "podcast", label: "Podcast", keywords: ["audio", "mic"], Icon: FiMic },
  { id: "calendar", label: "Calendar", keywords: ["date", "schedule"], Icon: FiCalendar },
  { id: "map", label: "Location", keywords: ["place", "pin"], Icon: FiMapPin },
  { id: "shopping", label: "Shop", keywords: ["store", "buy"], Icon: FiShoppingBag },
  { id: "gift", label: "Gift", keywords: ["present", "support"], Icon: FiGift },
  { id: "heart", label: "Heart", keywords: ["love", "favorite"], Icon: FiHeart },
  { id: "star", label: "Star", keywords: ["featured", "favorite"], Icon: FiStar },
  { id: "download", label: "Download", keywords: ["file", "save"], Icon: FiDownload },
  { id: "external", label: "External link", keywords: ["open", "outbound"], Icon: FiExternalLink },
  { id: "home", label: "Home", keywords: ["start", "main"], Icon: FiHome },
  { id: "user", label: "Profile", keywords: ["person", "account"], Icon: FiUser },
  { id: "settings", label: "Settings", keywords: ["config", "gear"], Icon: FiSettings },
  { id: "zap", label: "Lightning", keywords: ["fast", "energy"], Icon: FiZap },
  { id: "gamepad", label: "Gamepad", keywords: ["game", "gaming", "controller", "play"], Icon: FaGamepad },
  { id: "dice", label: "Dice", keywords: ["game", "random", "board"], Icon: FaDice },
  { id: "puzzle", label: "Puzzle", keywords: ["game", "piece", "logic"], Icon: FaPuzzlePiece },
  { id: "trophy", label: "Trophy", keywords: ["win", "award", "achievement"], Icon: FaTrophy },
  { id: "chess", label: "Chess", keywords: ["game", "board", "strategy"], Icon: FaChess },
  { id: "medal", label: "Medal", keywords: ["award", "achievement", "winner"], Icon: FaMedal },
  { id: "ghost_face", label: "Ghost", keywords: ["spooky", "halloween", "game"], Icon: FaGhost },
  { id: "dragon", label: "Dragon", keywords: ["fantasy", "game", "creature"], Icon: FaDragon },
  { id: "wand", label: "Magic wand", keywords: ["magic", "sparkle", "fantasy"], Icon: FaWandMagicSparkles },
  { id: "skull", label: "Skull", keywords: ["danger", "pirate", "game"], Icon: FaSkull },
  { id: "play", label: "Play", keywords: ["start", "media", "video"], Icon: FaPlay },
  { id: "pause", label: "Pause", keywords: ["media", "stop", "audio"], Icon: FaPause },
  { id: "film", label: "Film", keywords: ["movie", "cinema", "video"], Icon: FaFilm },
  { id: "clapperboard", label: "Clapperboard", keywords: ["movie", "film", "video"], Icon: FaClapperboard },
  { id: "ticket", label: "Ticket", keywords: ["event", "admission", "show"], Icon: FaTicket },
  { id: "guitar", label: "Guitar", keywords: ["music", "instrument", "band"], Icon: FaGuitar },
  { id: "drum", label: "Drum", keywords: ["music", "instrument", "beat"], Icon: FaDrum },
  { id: "theater", label: "Theater", keywords: ["drama", "masks", "performance"], Icon: FaMasksTheater },
  { id: "tv", label: "TV", keywords: ["television", "screen", "watch"], Icon: FaTv },
  { id: "radio", label: "Radio", keywords: ["broadcast", "audio", "fm"], Icon: FaRadio },
  { id: "headphones", label: "Headphones", keywords: ["audio", "music", "listen"], Icon: FaHeadphones },
  { id: "volume", label: "Volume", keywords: ["audio", "sound", "speaker"], Icon: FaVolumeHigh },
  { id: "podcast_show", label: "Podcast", keywords: ["audio", "show", "episode"], Icon: FaPodcast },
  { id: "blog", label: "Blog", keywords: ["writing", "post", "article"], Icon: FaBlog },
  { id: "comments", label: "Comments", keywords: ["chat", "discussion", "forum"], Icon: FaComments },
  { id: "share", label: "Share", keywords: ["social", "send", "network"], Icon: FaShareNodes },
  { id: "phone", label: "Phone", keywords: ["call", "mobile", "contact"], Icon: FaPhone },
  { id: "paper_plane", label: "Send", keywords: ["message", "submit", "share"], Icon: FaPaperPlane },
  { id: "hashtag", label: "Hashtag", keywords: ["social", "tag", "topic"], Icon: FaHashtag },
  { id: "chat", label: "Message", keywords: ["chat", "talk", "dm"], Icon: FaMessage },
  { id: "walkie_talkie", label: "Walkie-talkie", keywords: ["radio", "talk", "comms"], Icon: FaWalkieTalkie },
  { id: "newspaper", label: "News", keywords: ["article", "press", "media"], Icon: FaNewspaper },
  { id: "briefcase", label: "Briefcase", keywords: ["work", "job", "business"], Icon: FaBriefcase },
  { id: "award", label: "Award", keywords: ["badge", "honor", "win"], Icon: FaAward },
  { id: "certificate", label: "Certificate", keywords: ["credential", "course", "license"], Icon: FaCertificate },
  { id: "graduation_cap", label: "Graduation", keywords: ["school", "education", "degree"], Icon: FaGraduationCap },
  { id: "school", label: "School", keywords: ["education", "class", "learn"], Icon: FaSchool },
  { id: "chalkboard", label: "Chalkboard", keywords: ["teach", "class", "lesson"], Icon: FaChalkboard },
  { id: "pen", label: "Pen", keywords: ["write", "edit", "sign"], Icon: FaPen },
  { id: "feather", label: "Feather", keywords: ["write", "blog", "quill"], Icon: FaFeather },
  { id: "book_open", label: "Open book", keywords: ["read", "guide", "docs"], Icon: FaBookOpen },
  { id: "signature", label: "Signature", keywords: ["sign", "autograph", "name"], Icon: FaSignature },
  { id: "cart", label: "Cart", keywords: ["shop", "buy", "store"], Icon: FaCartShopping },
  { id: "wallet", label: "Wallet", keywords: ["money", "pay", "finance"], Icon: FaWallet },
  { id: "store", label: "Store", keywords: ["shop", "retail", "market"], Icon: FaStore },
  { id: "tag", label: "Tag", keywords: ["label", "price", "category"], Icon: FaTag },
  { id: "percent", label: "Percent", keywords: ["sale", "discount", "deal"], Icon: FaPercent },
  { id: "handshake", label: "Handshake", keywords: ["deal", "partner", "agreement"], Icon: FaHandshake },
  { id: "chart", label: "Chart", keywords: ["stats", "analytics", "growth"], Icon: FaChartLine },
  { id: "plane", label: "Plane", keywords: ["travel", "flight", "airport"], Icon: FaPlane },
  { id: "car", label: "Car", keywords: ["drive", "travel", "auto"], Icon: FaCar },
  { id: "bicycle", label: "Bicycle", keywords: ["bike", "cycle", "ride"], Icon: FaBicycle },
  { id: "ship", label: "Ship", keywords: ["boat", "travel", "ocean"], Icon: FaShip },
  { id: "train", label: "Train", keywords: ["transit", "rail", "travel"], Icon: FaTrain },
  { id: "compass", label: "Compass", keywords: ["direction", "navigate", "explore"], Icon: FaCompass },
  { id: "camping", label: "Camping", keywords: ["outdoors", "tent", "trail"], Icon: FaCampground },
  { id: "hiking", label: "Hiking", keywords: ["outdoors", "trail", "walk"], Icon: FaPersonHiking },
  { id: "route", label: "Route", keywords: ["map", "directions", "path"], Icon: FaRoute },
  { id: "landmark", label: "Landmark", keywords: ["monument", "place", "city"], Icon: FaLandmark },
  { id: "earth", label: "Earth", keywords: ["world", "global", "planet"], Icon: FaEarthAmericas },
  { id: "building", label: "Building", keywords: ["office", "company", "city"], Icon: FaBuilding },
  { id: "house", label: "House", keywords: ["home", "property", "real estate"], Icon: FaHouse },
  { id: "mountain", label: "Mountain", keywords: ["outdoors", "peak", "nature"], Icon: FaMountain },
  { id: "coffee", label: "Coffee", keywords: ["cafe", "drink", "mug"], Icon: FaMugHot },
  { id: "utensils", label: "Food", keywords: ["restaurant", "dining", "meal"], Icon: FaUtensils },
  { id: "pizza", label: "Pizza", keywords: ["food", "slice", "restaurant"], Icon: FaPizzaSlice },
  { id: "burger", label: "Burger", keywords: ["food", "fast food", "meal"], Icon: FaBurger },
  { id: "wine", label: "Wine", keywords: ["drink", "bar", "glass"], Icon: FaWineGlass },
  { id: "sun", label: "Sun", keywords: ["weather", "day", "bright"], Icon: FaSun },
  { id: "moon", label: "Moon", keywords: ["night", "dark", "sleep"], Icon: FaMoon },
  { id: "cloud", label: "Cloud", keywords: ["weather", "sky", "hosting"], Icon: FaCloud },
  { id: "tree", label: "Tree", keywords: ["nature", "forest", "plant"], Icon: FaTree },
  { id: "seedling", label: "Seedling", keywords: ["plant", "grow", "green"], Icon: FaSeedling },
  { id: "leaf", label: "Leaf", keywords: ["nature", "eco", "green"], Icon: FaLeaf },
  { id: "water", label: "Water", keywords: ["ocean", "pool", "liquid"], Icon: FaWater },
  { id: "paw", label: "Paw", keywords: ["pet", "animal", "dog"], Icon: FaPaw },
  { id: "cat", label: "Cat", keywords: ["pet", "animal", "kitten"], Icon: FaCat },
  { id: "dog", label: "Dog", keywords: ["pet", "animal", "puppy"], Icon: FaDog },
  { id: "fish", label: "Fish", keywords: ["animal", "sea", "aquarium"], Icon: FaFish },
  { id: "horse", label: "Horse", keywords: ["animal", "ride", "farm"], Icon: FaHorse },
  { id: "spider", label: "Spider", keywords: ["bug", "web", "halloween"], Icon: FaSpider },
  { id: "camera", label: "Camera", keywords: ["photo", "picture", "shoot"], Icon: FaCamera },
  { id: "paintbrush", label: "Paintbrush", keywords: ["art", "design", "paint"], Icon: FaPaintbrush },
  { id: "palette", label: "Palette", keywords: ["art", "color", "design"], Icon: FaPalette },
  { id: "brush", label: "Brush", keywords: ["art", "paint", "design"], Icon: FaBrush },
  { id: "scissors", label: "Scissors", keywords: ["cut", "craft", "trim"], Icon: FaScissors },
  { id: "ruler", label: "Ruler", keywords: ["measure", "design", "layout"], Icon: FaRuler },
  { id: "pen_nib", label: "Pen nib", keywords: ["write", "ink", "calligraphy"], Icon: FaPenNib },
  { id: "rocket", label: "Rocket", keywords: ["launch", "startup", "space"], Icon: FaRocket },
  { id: "lightbulb", label: "Lightbulb", keywords: ["idea", "tip", "innovation"], Icon: FaLightbulb },
  { id: "fire", label: "Fire", keywords: ["hot", "trending", "burn"], Icon: FaFire },
  { id: "bolt", label: "Bolt", keywords: ["power", "fast", "energy"], Icon: FaBolt },
  { id: "robot", label: "Robot", keywords: ["ai", "automation", "bot"], Icon: FaRobot },
  { id: "database", label: "Database", keywords: ["data", "storage", "sql"], Icon: FaDatabase },
  { id: "server", label: "Server", keywords: ["hosting", "backend", "infra"], Icon: FaServer },
  { id: "wifi", label: "Wi-Fi", keywords: ["network", "internet", "wireless"], Icon: FaWifi },
  { id: "microchip", label: "Microchip", keywords: ["hardware", "cpu", "tech"], Icon: FaMicrochip },
  { id: "console", label: "Console", keywords: ["terminal", "cli", "dev"], Icon: FaTerminal },
  { id: "keyboard", label: "Keyboard", keywords: ["type", "input", "hardware"], Icon: FaKeyboard },
  { id: "hard_drive", label: "Hard drive", keywords: ["storage", "disk", "backup"], Icon: FaHardDrive },
  { id: "ethernet", label: "Ethernet", keywords: ["network", "cable", "lan"], Icon: FaEthernet },
  { id: "qrcode", label: "QR code", keywords: ["scan", "link", "mobile"], Icon: FaQrcode },
  { id: "fingerprint", label: "Fingerprint", keywords: ["auth", "security", "identity"], Icon: FaFingerprint },
  { id: "plug", label: "Plug", keywords: ["power", "connect", "charge"], Icon: FaPlug },
  { id: "gear", label: "Gear", keywords: ["settings", "config", "tool"], Icon: FaGear },
  { id: "sliders", label: "Sliders", keywords: ["settings", "adjust", "controls"], Icon: FaSliders },
  { id: "dumbbell", label: "Dumbbell", keywords: ["fitness", "gym", "workout"], Icon: FaDumbbell },
  { id: "running", label: "Running", keywords: ["fitness", "sport", "run"], Icon: FaPersonRunning },
  { id: "heart_pulse", label: "Health", keywords: ["medical", "fitness", "pulse"], Icon: FaHeartPulse },
  { id: "stethoscope", label: "Stethoscope", keywords: ["medical", "doctor", "health"], Icon: FaStethoscope },
  { id: "microscope", label: "Microscope", keywords: ["science", "lab", "research"], Icon: FaMicroscope },
  { id: "flask", label: "Flask", keywords: ["science", "lab", "experiment"], Icon: FaFlask },
  { id: "brain", label: "Brain", keywords: ["mind", "ai", "think"], Icon: FaBrain },
  { id: "wheelchair", label: "Accessibility", keywords: ["access", "mobility", "a11y"], Icon: FaWheelchair },
  { id: "thumbs_up", label: "Thumbs up", keywords: ["like", "approve", "good"], Icon: FaThumbsUp },
  { id: "clap", label: "Applause", keywords: ["thanks", "celebrate", "support"], Icon: FaHandsClapping },
  { id: "peace", label: "Peace", keywords: ["calm", "vibes", "hand"], Icon: FaHandPeace },
  { id: "crown", label: "Crown", keywords: ["premium", "royal", "vip"], Icon: FaCrown },
  { id: "gem", label: "Gem", keywords: ["premium", "jewel", "value"], Icon: FaGem },
  { id: "flag", label: "Flag", keywords: ["mark", "report", "milestone"], Icon: FaFlag },
  { id: "bookmark", label: "Bookmark", keywords: ["save", "read later", "favorite"], Icon: FaBookmark },
  { id: "bell", label: "Bell", keywords: ["notify", "alert", "news"], Icon: FaBell },
  { id: "lock", label: "Lock", keywords: ["secure", "private", "auth"], Icon: FaLock },
  { id: "key", label: "Key", keywords: ["unlock", "access", "password"], Icon: FaKey },
  { id: "shield", label: "Shield", keywords: ["security", "safe", "protect"], Icon: FaShieldHalved },
  { id: "eye", label: "Eye", keywords: ["view", "watch", "preview"], Icon: FaEye },
  { id: "glasses", label: "Glasses", keywords: ["read", "style", "vision"], Icon: FaGlasses },
  { id: "toolbox", label: "Toolbox", keywords: ["tools", "repair", "build"], Icon: FaToolbox },
  { id: "hammer", label: "Hammer", keywords: ["build", "fix", "tool"], Icon: FaHammer },
  { id: "recycle", label: "Recycle", keywords: ["eco", "reuse", "green"], Icon: FaRecycle },
  { id: "search", label: "Search", keywords: ["find", "lookup", "magnify"], Icon: FaMagnifyingGlass },
  { id: "copy", label: "Copy", keywords: ["duplicate", "clipboard", "clone"], Icon: FaCopy },
  { id: "clipboard", label: "Clipboard", keywords: ["notes", "list", "paste"], Icon: FaClipboard },
  { id: "paperclip", label: "Paperclip", keywords: ["attach", "file", "link"], Icon: FaPaperclip },
  { id: "box", label: "Box", keywords: ["package", "ship", "product"], Icon: FaBox },
  { id: "cube", label: "Cube", keywords: ["3d", "block", "module"], Icon: FaCube },
  { id: "truck", label: "Truck", keywords: ["delivery", "shipping", "logistics"], Icon: FaTruck },
  { id: "list", label: "List", keywords: ["items", "menu", "bullet"], Icon: FaList },
  { id: "layers", label: "Layers", keywords: ["stack", "design", "layout"], Icon: FiLayers },
  { id: "anchor", label: "Anchor", keywords: ["link", "maritime", "hold"], Icon: FaAnchor },
  { id: "clock", label: "Clock", keywords: ["time", "schedule", "hours"], Icon: FaClock },
  { id: "umbrella", label: "Umbrella", keywords: ["weather", "rain", "cover"], Icon: FaUmbrella },
  { id: "tablet", label: "Tablet", keywords: ["device", "mobile", "screen"], Icon: FaTablet },
  { id: "laptop", label: "Laptop", keywords: ["computer", "device", "work"], Icon: FaLaptop },
  { id: "microphone", label: "Microphone", keywords: ["audio", "record", "voice"], Icon: FaMicrophone },
  { id: "satellite", label: "Satellite", keywords: ["space", "signal", "broadcast"], Icon: FaSatellite },
  { id: "helicopter", label: "Helicopter", keywords: ["flight", "travel", "air"], Icon: FaHelicopter },
  { id: "people", label: "People", keywords: ["team", "group", "community"], Icon: FaPeopleGroup },
  { id: "child", label: "Child", keywords: ["kids", "family", "young"], Icon: FaChild },
  { id: "ribbon", label: "Ribbon", keywords: ["award", "cause", "support"], Icon: FaRibbon },
  { id: "stamp", label: "Stamp", keywords: ["approved", "official", "mail"], Icon: FaStamp },
  { id: "target", label: "Target", keywords: ["goal", "aim", "focus"], Icon: FaBullseye },
  { id: "location", label: "Location", keywords: ["pin", "place", "address"], Icon: FaLocationDot },
  { id: "trending", label: "Trending", keywords: ["growth", "stats", "popular"], Icon: FiTrendingUp },
  { id: "package", label: "Package", keywords: ["box", "delivery", "parcel"], Icon: FiPackage },
  { id: "tool", label: "Tool", keywords: ["fix", "build", "utility"], Icon: FiTool },
  { id: "monitor", label: "Monitor", keywords: ["screen", "desktop", "display"], Icon: FiMonitor },
  { id: "smartphone", label: "Smartphone", keywords: ["mobile", "phone", "app"], Icon: FiSmartphone },
  { id: "watch", label: "Watch", keywords: ["time", "wearable", "clock"], Icon: FiWatch },
  { id: "speaker", label: "Speaker", keywords: ["audio", "sound", "music"], Icon: FiSpeaker },
  { id: "fi_headphones", label: "Headphones alt", keywords: ["audio", "listen", "music"], Icon: FiHeadphones },
  { id: "fi_phone", label: "Phone alt", keywords: ["call", "mobile", "contact"], Icon: FiPhone },
  { id: "fi_send", label: "Send alt", keywords: ["message", "submit", "mail"], Icon: FiSend },
  { id: "fi_share", label: "Share alt", keywords: ["social", "forward", "send"], Icon: FiShare2 },
  { id: "fi_users", label: "Users", keywords: ["team", "group", "people"], Icon: FiUsers },
  { id: "fi_film", label: "Film alt", keywords: ["movie", "video", "media"], Icon: FiFilm },
  { id: "fi_play", label: "Play alt", keywords: ["start", "media", "video"], Icon: FiPlay },
  { id: "fi_compass", label: "Compass alt", keywords: ["navigate", "explore", "direction"], Icon: FiCompass },
  { id: "fi_flag", label: "Flag alt", keywords: ["mark", "report", "goal"], Icon: FiFlag },
  { id: "fi_bookmark", label: "Bookmark alt", keywords: ["save", "favorite", "read"], Icon: FiBookmark },
  { id: "fi_target", label: "Target alt", keywords: ["goal", "aim", "focus"], Icon: FiTarget },
  { id: "fi_shield", label: "Shield alt", keywords: ["security", "safe", "protect"], Icon: FiShield },
  { id: "fi_credit_card", label: "Credit card", keywords: ["pay", "billing", "checkout"], Icon: FiCreditCard },
  { id: "fi_trash", label: "Trash", keywords: ["delete", "remove", "bin"], Icon: FiTrash2 },
  { id: "fi_coffee", label: "Coffee alt", keywords: ["cafe", "drink", "break"], Icon: FiCoffee },
  { id: "fi_sun", label: "Sun alt", keywords: ["day", "weather", "bright"], Icon: FiSun },
  { id: "fi_clock", label: "Clock alt", keywords: ["time", "schedule", "hours"], Icon: FiClock },
  { id: "fi_feather", label: "Feather alt", keywords: ["write", "blog", "light"], Icon: FiFeather },
];

const MEDIA_ICON_MAP = new Map(MEDIA_ICONS.map((entry) => [entry.id, entry]));

export function isMediaIconId(value: string): value is string {
  return MEDIA_ICON_MAP.has(value);
}

export function getMediaIcon(id: string): MediaIconEntry | undefined {
  return MEDIA_ICON_MAP.get(id);
}

export function searchMediaIcons(query: string): MediaIconEntry[] {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) return MEDIA_ICONS;

  return MEDIA_ICONS.filter((entry) => {
    if (entry.id.includes(trimmed)) return true;
    if (entry.label.toLowerCase().includes(trimmed)) return true;
    return entry.keywords.some((keyword) => keyword.includes(trimmed));
  });
}
